services:
  jupyter:
    image: quay.io/jupyter/datascience-notebook:2024-04-29
    ports:
      - "10000:8888"
    volumes:
      - ${PWD}:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
